
server:
  port: 8093
  servlet:
    context-path: /learning

spring:
  application:
    name:  test
  messages:
    basename: messages,messages_sys,messages_mst
    encoding: UTF-8
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat
      testOnReturn: false
      testWhileIdle: true
      maxActive: 1
      removeAbandonedTimeoutMillis: 1
      name: datasource
      testOnBorrow: false
      minIdle: 1
      initialSize: 1
      poolPreparedStatements: true
      url: jdbc:mysql://58.87.106.44:3306/tms?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      validationQuery: select 1
      maxOpenPreparedStatements: 300
      username: root
      password: 'Hsql~112233'
  jackson:
    default-property-inclusion: non_null
#logging:
#  level:
#    root: trace

feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: mapper/*.xml
